# docker-compose.yml
version: '3'
services:
  flashcards:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8090:8090"
    image: mat/flashcards:latest
    container_name: flashcards
    networks:
      - cloudflare
    volumes:
      - ./DB-out-of-docker:/app/databases 
    environment:
      - ENV=production

networks:
  cloudflare:
    external: true
